trigger:
- master

variables:
  awxUsername: ansibleuser
  awxPassword: ansible
  jobTemplateId: 9

steps: 
  - script: |
      echo 'running the Ansible tower job'
      echo $(test)
      curl -XPOST http://3.238.58.152/api/v2/job_templates/$(jobTemplateId)/launch/ -u '$(awxUsername):$(awxPassword)'
